### ISSUE TITLE
Filter for own recipes

### ISSUE THREAD

**Issue by sepulzera** [ownrecipes/OwnRecipes#58]
Provide a new search-filter to only show own recipes.

**Comment by sepulzera** [comment]
The api could provide a "author" filter. The frontend could then search for the own author.

**Comment by Lominex** [comment]
@sepulzera can i give this issue a try?

**Comment by sepulzera** [comment]
Sure! As a starting point, have a look at the file ownrecipes-api/v1/recipe/views.py, class RecipeViewSet. Do not forget to write some tests and to reflect your change in the OpenAPI file ownrecipes-api/docs/ownrecipes-api.json. Let me know if you need more information.

For the frontend part, it would be the file ownrecipes-web/src/browse/SearchMenu.tsx. We could add new filter group "General" with a filter "My recipes". There is currently no API-query to fetch the sum for that, thus we could just leave the count. (Currently [filter with no sum will be removed](https://github.com/ownrecipes/ownrecipes-web/blob/development/src/browse/components/Filter.tsx#L51-L53), we should also take a look into that.

If you would only like to do the api part, then I could do the frontend stuff, too.

**Comment by Lominex** [comment]
Hey i'am having trouble setting up the system with Docker.
I followed your docs but cant figure out what i am doing wrong.
After initial start-up i get following error from the site:
```
cannot GET http://192.168.178.49:8000/api/v1/recipe/mini-browse/?fields=id,slug,title,pub_date,rating,photo_thumbnail,info&limit=4 (500)
```
and the api container gives this error log:
```
![Bildschirmfoto vom 2023-01-05 07-37-08](https://user-images.githubusercontent.com/73841042/210718767-dae668d6-5794-468b-913b-baed68540005.png)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1045, "Access denied for user 'root'@'172.18.0.3' (using password: YES)")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/code/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.8/site-packages/django/core/management/__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/usr/local/lib/python3.8/site-packages/django/core/management/base.py", line 419, in check
    all_issues = checks.run_checks(
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/registry.py", line 76, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/site-packages/django/core/checks/model_checks.py", line 34, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1303, in check
    *cls._check_indexes(databases),
  File "/usr/local/lib/python3.8/site-packages/django/db/models/base.py", line 1711, in _check_indexes
    connection.features.supports_expression_indexes or
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/features.py", line 253, in supports_expression_indexes
    not self.connection.mysql_is_mariadb and
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 401, in mysql_is_mariadb
    return 'mariadb' in self.mysql_server_info.lower()
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 390, in mysql_server_info
    return self.mysql_server_data['version']
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 366, in mysql_server_data
    with self.temporary_connection() as cursor:
  File "/usr/local/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 603, in temporary_connection
    with self.cursor() as cursor:
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 259, in cursor
    return self._cursor()
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 235, in _cursor
    self.ensure_connection()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 219, in ensure_connection
    self.connect()
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/base/base.py", line 200, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/usr/local/lib/python3.8/site-packages/django/utils/asyncio.py", line 33, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/mysql/base.py", line 234, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/__init__.py", line 123, in Connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/MySQLdb/connections.py", line 185, in __init__
    super().__init__(*args, **kwargs2)
django.db.utils.OperationalError: (1045, "Access denied for user 'root'@'172.18.0.3' (using password: YES)")

0 static files copied to '/code/static-files', 163 unmodified.
Starting OwnRecipes as root
[2023-01-05 06:35:17 +0000] [10] [INFO] Starting gunicorn 20.1.0
[2023-01-05 06:35:17 +0000] [10] [INFO] Listening at: http://0.0.0.0:8000 (10)
[2023-01-05 06:35:17 +0000] [10] [INFO] Using worker: sync
[2023-01-05 06:35:17 +0000] [13] [INFO] Booting worker with pid: 13
[2023-01-05 06:35:17 +0000] [14] [INFO] Booting worker with pid: 14
[2023-01-05 06:35:17 +0000] [15] [INFO] Booting worker with pid: 15
[2023-01-05 06:35:17 +0000] [16] [INFO] Booting worker with pid: 16
[2023-01-05 06:35:17 +0000] [17] [INFO] Booting worker with pid: 17
```

**Comment by sepulzera** [comment]
> MySQLdb.OperationalError: (1045, "Access denied for user 'root'@'172.18.0.3' (using password: YES)")

I guess you ran the production build with another db password. You could use the same password, or change the database name. If this doesn't help, I would please you to open a separate issue for it, to keep things clean here.

**Comment by sepulzera** [comment]
@Lominex Hey, how is it going?
